In [3]:
import pandas as pd

# Step 1: Import the CSV files
df_2020 = pd.read_csv(r'C:\Users\siddi\OneDrive\Documents\SMU Homework\HW5+Aug12\athletic_sales_analysis\athletic_sales_2020.csv')
df_2021 = pd.read_csv(r'C:\Users\siddi\OneDrive\Documents\SMU Homework\HW5+Aug12\athletic_sales_analysis\athletic_sales_2021.csv')

# Step 2: Check columns and data types
print("2020 Data Columns and Types:\n", df_2020.dtypes)
print("2021 Data Columns and Types:\n", df_2021.dtypes)

# Step 3: Combine the DataFrames by rows and reset index
df_combined = pd.concat([df_2020, df_2021], ignore_index=True)

# Step 4: Check for null values
print("Null values in combined DataFrame:\n", df_combined.isnull().sum())

# Step 5: Convert 'invoice_date' to datetime and confirm the change
df_combined['invoice_date'] = pd.to_datetime(df_combined['invoice_date'], format='%Y-%m-%d', errors='coerce')
print("Data types after conversion:\n", df_combined.dtypes)

# Determine which Region Sold the Most Products
region_sales = df_combined.groupby(['region', 'state', 'city'])['units_sold'].sum().reset_index()
region_sales.rename(columns={'units_sold': 'Total_Products_Sold'}, inplace=True)
top_regions = region_sales.sort_values(by='Total_Products_Sold', ascending=False).head(5)
print("Top 5 Regions by Units Sold:\n", top_regions)

# Determine which Region had the Most Sales
region_sales_amount = df_combined.groupby(['region', 'state', 'city'])['total_sales'].sum().reset_index()
region_sales_amount.rename(columns={'total_sales': 'Total_Sales_Amount'}, inplace=True)
top_sales_regions = region_sales_amount.sort_values(by='Total_Sales_Amount', ascending=False).head(5)
print("Top 5 Regions by Sales Amount:\n", top_sales_regions)

# Determine which Retailer had the Most Sales
retailer_sales = df_combined.groupby(['retailer', 'region', 'state', 'city'])['total_sales'].sum().reset_index()
retailer_sales.rename(columns={'total_sales': 'Total_Sales_Amount'}, inplace=True)
top_retailers = retailer_sales.sort_values(by='Total_Sales_Amount', ascending=False).head(5)
print("Top 5 Retailers by Sales Amount:\n", top_retailers)

# Determine which Retailer Sold the Most Women's Athletic Footwear
womens_footwear = df_combined[df_combined['product'] == "Women's Athletic Footwear"]
womens_footwear_sales = womens_footwear.groupby(['retailer', 'region', 'state', 'city'])['units_sold'].sum().reset_index()
womens_footwear_sales.rename(columns={'units_sold': 'Womens_Footwear_Units_Sold'}, inplace=True)
top_womens_footwear_retailers = womens_footwear_sales.sort_values(by='Womens_Footwear_Units_Sold', ascending=False).head(5)
print("Top 5 Retailers by Women's Athletic Footwear Units Sold:\n", top_womens_footwear_retailers)

# Determine the Day with the Most Women's Athletic Footwear Sales
daily_sales = womens_footwear.groupby('invoice_date')['total_sales'].sum().reset_index()
daily_sales.set_index('invoice_date', inplace=True)
daily_sales_resampled = daily_sales.resample('D').sum()
daily_sales_resampled.rename(columns={'total_sales': 'Daily_Total_Sales'}, inplace=True)

# Sort the resampled DataFrame in descending order to show the top 10 days
top_days = daily_sales_resampled.sort_values(by='Daily_Total_Sales', ascending=False).head(10)
print("Top 10 Days by Women's Athletic Footwear Sales:\n", top_days)

# Determine the Week with the Most Women's Athletic Footwear Sales
weekly_sales_resampled = daily_sales_resampled.resample('W').sum()
weekly_sales_resampled.rename(columns={'Daily_Total_Sales': 'Weekly_Total_Sales'}, inplace=True)

# Sort the resampled DataFrame in descending order to show the top 10 weeks
top_weeks = weekly_sales_resampled.sort_values(by='Weekly_Total_Sales', ascending=False).head(10)
print("Top 10 Weeks by Women's Athletic Footwear Sales:\n", top_weeks)

2020 Data Columns and Types:
 retailer             object
retailer_id           int64
invoice_date         object
region               object
state                object
city                 object
product              object
price_per_unit        int64
units_sold            int64
total_sales           int64
operating_profit    float64
sales_method         object
dtype: object
2021 Data Columns and Types:
 retailer             object
retailer_id           int64
invoice_date         object
region               object
state                object
city                 object
product              object
price_per_unit        int64
units_sold            int64
total_sales           int64
operating_profit    float64
sales_method         object
dtype: object
Null values in combined DataFrame:
 retailer            0
retailer_id         0
invoice_date        0
region              0
state               0
city                0
product             0
price_per_unit      0
units_sold          0
total_sales         0
operating_profit    0
sales_method        0
dtype: int64
Data types after conversion:
 retailer                    object
retailer_id                  int64
invoice_date        datetime64[ns]
region                      object
state                       object
city                        object
product                     object
price_per_unit               int64
units_sold                   int64
total_sales                  int64
operating_profit           float64
sales_method                object
dtype: object
Top 5 Regions by Units Sold:
        region       state           city  Total_Products_Sold
21  Northeast    New York       New York               111954
33      South       Texas        Houston                90322
44       West  California  San Francisco                85478
43       West  California    Los Angeles                76384
34  Southeast     Florida          Miami                73135
Top 5 Regions by Sales Amount:
        region           state           city  Total_Sales_Amount
21  Northeast        New York       New York            39801235
44       West      California  San Francisco            33973228
34  Southeast         Florida          Miami            31600863
39  Southeast  South Carolina     Charleston            29285637
35  Southeast         Florida        Orlando            27682851
Top 5 Retailers by Sales Amount:
         retailer     region           state           city  Total_Sales_Amount
103    West Gear       West      California  San Francisco            32794405
50        Kohl's       West      California    Los Angeles            25127160
22   Foot Locker  Northeast        New York       New York            25008568
109    West Gear       West      Washington        Seattle            24862675
33   Foot Locker  Southeast  South Carolina     Charleston            24822280
Top 5 Retailers by Women's Athletic Footwear Units Sold:
           retailer     region           state           city  \
101      West Gear       West      California  San Francisco
22     Foot Locker  Northeast        New York       New York
49          Kohl's       West      California    Los Angeles
33     Foot Locker  Southeast  South Carolina     Charleston
68   Sports Direct      South           Texas         Dallas

     Womens_Footwear_Units_Sold
101                       12107
22                        10996
49                        10826
33                         8814
68                         8790
Top 10 Days by Women's Athletic Footwear Sales:
 Empty DataFrame
Columns: [Daily_Total_Sales]
Index: []
Top 10 Weeks by Women's Athletic Footwear Sales:
 Empty DataFrame
Columns: [Weekly_Total_Sales]
Index: []